import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ExternalLink, Printer, FileDown, ShieldAlert, Clock, EyeOff, Undo2, Lock, FileText } from "lucide-react";

export default function PrivacyPolicy() {
  const currentYear = new Date().getFullYear();
  const lastUpdated = "March 30, 2025";
  
  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <div className="flex justify-between items-start">
          <h1 className="text-4xl font-extrabold tracking-tight">Privacy Policy</h1>
          <div className="flex space-x-2">
            <Button variant="outline" size="sm" onClick={() => window.print()}>
              <Printer className="h-4 w-4 mr-2" />
              Print
            </Button>
            <Button variant="outline" size="sm">
              <FileDown className="h-4 w-4 mr-2" />
              Download
            </Button>
          </div>
        </div>
        <p className="text-muted-foreground">
          Last updated: {lastUpdated}
        </p>
      </div>

      <div className="bg-primary/5 border border-primary/10 rounded-lg p-4 flex items-start space-x-3">
        <ShieldAlert className="h-5 w-5 text-orange-500 mt-0.5 flex-shrink-0" />
        <div>
          <h3 className="font-medium text-foreground mb-1">Your Privacy Is Important To Us</h3>
          <p className="text-sm text-muted-foreground">
            This privacy policy explains how Ecom Hawks collects, uses, processes, discloses, and safeguards
            your information when you use our Amazon PPC Optimizer tool. Please read this policy carefully.
            If you do not agree with the terms of this privacy policy, please do not access the application.
          </p>
        </div>
      </div>

      <Tabs defaultValue="general" className="w-full">
        <TabsList className="w-full grid grid-cols-3 md:grid-cols-6 lg:w-auto">
          <TabsTrigger value="general">General</TabsTrigger>
          <TabsTrigger value="collection">Data Collection</TabsTrigger>
          <TabsTrigger value="usage">Data Usage</TabsTrigger>
          <TabsTrigger value="sharing">Data Sharing</TabsTrigger>
          <TabsTrigger value="security">Security</TabsTrigger>
          <TabsTrigger value="rights">Your Rights</TabsTrigger>
        </TabsList>

        <Card className="mt-6 border-t-0 rounded-t-none">
          <CardContent className="pt-6">
            <ScrollArea className="h-[600px] pr-4">
              <TabsContent value="general" className="mt-0">
                <div className="space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold mb-3">Introduction</h2>
                    <p className="text-muted-foreground mb-3">
                      Ecom Hawks ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains our practices regarding the collection, use, and disclosure of information that we receive when you use our Amazon PPC Optimizer tool (the "Service").
                    </p>
                    <p className="text-muted-foreground mb-3">
                      This policy applies to all information collected through our Service, as well as any related services, sales, marketing, or events.
                    </p>
                    <p className="text-muted-foreground">
                      By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms of Service.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Definitions</h2>
                    <p className="text-muted-foreground mb-3">
                      <strong>Service</strong> refers to the Amazon PPC Optimizer application.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      <strong>Personal Data</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                    </p>
                    <p className="text-muted-foreground mb-3">
                      <strong>Usage Data</strong> refers to data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                    </p>
                    <p className="text-muted-foreground mb-3">
                      <strong>Cookies</strong> are small pieces of data stored on your device (computer or mobile device).
                    </p>
                    <p className="text-muted-foreground">
                      <strong>Data Controller</strong> means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Changes To This Privacy Policy</h2>
                    <p className="text-muted-foreground mb-3">
                      We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "last updated" date at the top of this Privacy Policy.
                    </p>
                    <p className="text-muted-foreground">
                      You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                    </p>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="collection" className="mt-0">
                <div className="space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold mb-3">Information Collection</h2>
                    <p className="text-muted-foreground mb-3">
                      We collect several different types of information for various purposes to provide and improve our Service to you.
                    </p>
                  </div>

                  <div>
                    <h3 className="text-lg font-medium mb-2">Personal Data</h3>
                    <p className="text-muted-foreground mb-3">
                      While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1 mb-3">
                      <li>Email address</li>
                      <li>First name and last name</li>
                      <li>Phone number</li>
                      <li>Company name</li>
                      <li>Address, State, Province, ZIP/Postal code, City</li>
                      <li>Cookies and Usage Data</li>
                    </ul>
                    <p className="text-muted-foreground">
                      We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.
                    </p>
                  </div>

                  <div>
                    <h3 className="text-lg font-medium mb-2">Usage Data</h3>
                    <p className="text-muted-foreground mb-3">
                      We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").
                    </p>
                    <p className="text-muted-foreground mb-3">
                      This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                    </p>
                    <p className="text-muted-foreground">
                      When you access the Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
                    </p>
                  </div>

                  <div>
                    <h3 className="text-lg font-medium mb-2">Tracking & Cookies Data</h3>
                    <p className="text-muted-foreground mb-3">
                      We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      Examples of Cookies we use:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                      <li><strong>Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
                      <li><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                      <li><strong>Security Cookies:</strong> We use Security Cookies for security purposes.</li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="text-lg font-medium mb-2">Amazon Advertising Data</h3>
                    <p className="text-muted-foreground mb-3">
                      With your consent, we collect data from your Amazon Advertising account, including campaign performance metrics, keywords, targeting settings, budgets, and other related advertising data. This data is collected either through:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1 mb-3">
                      <li>CSV files that you upload to our Service; or</li>
                      <li>Direct API integration with Amazon Advertising, if you have authorized such access</li>
                    </ul>
                    <p className="text-muted-foreground">
                      This data is used specifically to provide the core functionality of our Service, which includes analyzing your advertising performance, generating insights and recommendations, and optimizing your advertising campaigns.
                    </p>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="usage" className="mt-0">
                <div className="space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold mb-3">Use of Data</h2>
                    <p className="text-muted-foreground mb-3">
                      Ecom Hawks uses the collected data for various purposes:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                      <li>To provide and maintain our Service</li>
                      <li>To notify you about changes to our Service</li>
                      <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                      <li>To provide customer support</li>
                      <li>To gather analysis or valuable information so that we can improve our Service</li>
                      <li>To monitor the usage of our Service</li>
                      <li>To detect, prevent and address technical issues</li>
                      <li>To analyze and optimize your Amazon advertising campaigns</li>
                      <li>To generate reports and insights about your advertising performance</li>
                      <li>To provide personalized recommendations for improving your advertising campaigns</li>
                      <li>To fulfill any other purpose for which you provide it</li>
                      <li>To carry out our obligations and enforce our rights</li>
                      <li>To provide you with notices about your account</li>
                      <li>To provide you with news, special offers and general information about other goods, services and events which we offer</li>
                      <li>For any other purpose with your consent</li>
                    </ul>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Legal Basis for Processing Personal Data Under GDPR</h2>
                    <p className="text-muted-foreground mb-3">
                      If you are from the European Economic Area (EEA), Ecom Hawks's legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      Ecom Hawks may process your Personal Data because:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                      <li>We need to perform a contract with you</li>
                      <li>You have given us permission to do so</li>
                      <li>The processing is in our legitimate interests and it's not overridden by your rights</li>
                      <li>For payment processing purposes</li>
                      <li>To comply with the law</li>
                    </ul>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Retention of Data</h2>
                    <p className="text-muted-foreground mb-3">
                      Ecom Hawks will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      Ecom Hawks will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                    </p>
                    <p className="text-muted-foreground">
                      Your Amazon Advertising data will be retained for the duration of your active subscription and for a period of 30 days after subscription termination or cancellation, after which it will be deleted from our systems unless you have requested otherwise or we are required by law to retain it.
                    </p>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="sharing" className="mt-0">
                <div className="space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold mb-3">Disclosure of Data</h2>
                    <p className="text-muted-foreground mb-3">
                      We may disclose personal information that we collect, or you provide:
                    </p>
                  </div>

                  <div>
                    <h3 className="text-lg font-medium mb-2">Business Transaction</h3>
                    <p className="text-muted-foreground mb-3">
                      If Ecom Hawks is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.
                    </p>
                  </div>

                  <div>
                    <h3 className="text-lg font-medium mb-2">Disclosure for Law Enforcement</h3>
                    <p className="text-muted-foreground mb-3">
                      Under certain circumstances, Ecom Hawks may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                    </p>
                  </div>

                  <div>
                    <h3 className="text-lg font-medium mb-2">Legal Requirements</h3>
                    <p className="text-muted-foreground mb-3">
                      Ecom Hawks may disclose your Personal Data in the good faith belief that such action is necessary to:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                      <li>To comply with a legal obligation</li>
                      <li>To protect and defend the rights or property of Ecom Hawks</li>
                      <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                      <li>To protect the personal safety of users of the Service or the public</li>
                      <li>To protect against legal liability</li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="text-lg font-medium mb-2">Service Providers</h3>
                    <p className="text-muted-foreground mb-3">
                      We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                    </p>
                  </div>

                  <div>
                    <h3 className="text-lg font-medium mb-2">Analytics</h3>
                    <p className="text-muted-foreground mb-3">
                      We may use third-party Service Providers to monitor and analyze the use of our Service.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      <strong>Google Analytics:</strong> Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.
                    </p>
                    <p className="text-muted-foreground">
                      For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">https://policies.google.com/privacy</a>
                    </p>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="security" className="mt-0">
                <div className="space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold mb-3">Security of Data</h2>
                    <p className="text-muted-foreground mb-3">
                      The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      We implement a variety of security measures to maintain the safety of your personal information when you enter, submit, or access your personal information, including:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                      <li>All sensitive information you provide is encrypted via Secure Socket Layer (SSL) technology.</li>
                      <li>All data is stored in secure cloud environments with appropriate access controls.</li>
                      <li>We regularly review our information collection, storage and processing practices to guard against unauthorized access.</li>
                      <li>We restrict access to personal information to our employees, contractors and agents who need to know that information in order to process it, and who are subject to strict contractual confidentiality obligations.</li>
                    </ul>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Data Breach</h2>
                    <p className="text-muted-foreground mb-3">
                      In the event we become aware that the security of the Service has been compromised or users' Personal Data has been disclosed to unrelated third parties as a result of external activity, including, but not limited to, security attacks or fraud, we reserve the right to take reasonably appropriate measures, including, but not limited to, investigation and reporting, as well as notification to and cooperation with law enforcement authorities.
                    </p>
                    <p className="text-muted-foreground">
                      In the event of a data breach, we will make reasonable efforts to notify affected individuals if we believe that there is a reasonable risk of harm to the user as a result of the breach or if notice is otherwise required by law. When we do, we will send you an email.
                    </p>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="rights" className="mt-0">
                <div className="space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold mb-3">Your Data Protection Rights Under GDPR</h2>
                    <p className="text-muted-foreground mb-3">
                      If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Ecom Hawks aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      In certain circumstances, you have the following data protection rights:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1 mb-3">
                      <li><strong>The right to access, update or to delete</strong> the information we have on you.</li>
                      <li><strong>The right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
                      <li><strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.</li>
                      <li><strong>The right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</li>
                      <li><strong>The right to data portability.</strong> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</li>
                      <li><strong>The right to withdraw consent.</strong> You also have the right to withdraw your consent at any time where Ecom Hawks relied on your consent to process your personal information.</li>
                    </ul>
                    <p className="text-muted-foreground">
                      Please note that we may ask you to verify your identity before responding to such requests.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Your Data Protection Rights Under CCPA</h2>
                    <p className="text-muted-foreground mb-3">
                      If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1 mb-3">
                      <li><strong>What personal information we have about you.</strong> If you make this request, we will return to you:
                        <ul className="list-disc pl-6 mt-1">
                          <li>The categories of personal information we have collected about you.</li>
                          <li>The categories of sources from which we collect your personal information.</li>
                          <li>The business or commercial purpose for collecting or selling your personal information.</li>
                          <li>The categories of third parties with whom we share personal information.</li>
                          <li>The specific pieces of personal information we have collected about you.</li>
                          <li>A list of categories of personal information that we have sold, along with the category of any other company we sold it to.</li>
                          <li>A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.</li>
                        </ul>
                      </li>
                      <li><strong>To delete your personal information.</strong> If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.</li>
                      <li><strong>To stop selling your personal information.</strong> We don't sell or rent your personal information to any third parties for any purpose. We do not sell your personal information for monetary consideration. However, under some state laws, sharing your data through third-party cookies for online advertising may be considered a "sale" of information. You can learn more about how this works in our Cookie Policy section. In addition, you can control certain cookies using our privacy preferences link, or through the browser you are using. For more information, please see our Cookie Policy.</li>
                    </ul>
                    <p className="text-muted-foreground">
                      Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Children's Privacy</h2>
                    <p className="text-muted-foreground mb-3">
                      Our Service does not address anyone under the age of 18 ("Children").
                    </p>
                    <p className="text-muted-foreground mb-3">
                      We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Contact Us</h2>
                    <p className="text-muted-foreground mb-3">
                      If you have any questions about this Privacy Policy, please contact us:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                      <li>By email: support@ecomhawks.com</li>
                      <li>By phone: +1 (555) 123-4567</li>
                      <li>By mail: Ecom Hawks, 123 Market Street, Suite 456, San Francisco, CA 94105</li>
                    </ul>
                  </div>
                </div>
              </TabsContent>
            </ScrollArea>
          </CardContent>
        </Card>
      </Tabs>

      <div className="flex justify-between items-center p-4 bg-primary/5 border border-primary/10 rounded-lg">
        <div className="flex items-center space-x-3">
          <Clock className="h-5 w-5 text-muted-foreground" />
          <p className="text-sm text-muted-foreground">
            This privacy policy was last updated on {lastUpdated}.
          </p>
        </div>
        <div className="flex items-center space-x-3">
          <Button variant="outline" size="sm" asChild>
            <a href="/terms-of-service">
              <FileText className="h-4 w-4 mr-2" />
              Terms of Service
            </a>
          </Button>
        </div>
      </div>
    </div>
  );
}