import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ExternalLink, Printer, FileDown, AlertTriangle, Clock, Shield, Scale, FileText } from "lucide-react";

export default function TermsOfService() {
  const currentYear = new Date().getFullYear();
  const lastUpdated = "March 30, 2025";
  
  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <div className="flex justify-between items-start">
          <h1 className="text-4xl font-extrabold tracking-tight">Terms of Service</h1>
          <div className="flex space-x-2">
            <Button variant="outline" size="sm" onClick={() => window.print()}>
              <Printer className="h-4 w-4 mr-2" />
              Print
            </Button>
            <Button variant="outline" size="sm">
              <FileDown className="h-4 w-4 mr-2" />
              Download
            </Button>
          </div>
        </div>
        <p className="text-muted-foreground">
          Last updated: {lastUpdated}
        </p>
      </div>

      <div className="bg-primary/5 border border-primary/10 rounded-lg p-4 flex items-start space-x-3">
        <AlertTriangle className="h-5 w-5 text-orange-500 mt-0.5 flex-shrink-0" />
        <div>
          <h3 className="font-medium text-foreground mb-1">Agreement to Our Legal Terms</h3>
          <p className="text-sm text-muted-foreground">
            These Terms of Service ("Terms") govern your access to and use of the Amazon PPC Optimizer application provided by Ecom Hawks. 
            Please read these Terms carefully before using our Service. By accessing or using our Service, you agree to be bound by these Terms.
            If you disagree with any part of the terms, you may not access the Service.
          </p>
        </div>
      </div>

      <Tabs defaultValue="overview" className="w-full">
        <TabsList className="w-full grid grid-cols-2 md:grid-cols-6 lg:w-auto">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="account">Account</TabsTrigger>
          <TabsTrigger value="service">Service</TabsTrigger>
          <TabsTrigger value="limitations">Limitations</TabsTrigger>
          <TabsTrigger value="intellectual">Intellectual Property</TabsTrigger>
          <TabsTrigger value="legal">Legal</TabsTrigger>
        </TabsList>

        <Card className="mt-6 border-t-0 rounded-t-none">
          <CardContent className="pt-6">
            <ScrollArea className="h-[600px] pr-4">
              <TabsContent value="overview" className="mt-0">
                <div className="space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold mb-3">Introduction</h2>
                    <p className="text-muted-foreground mb-3">
                      Welcome to Ecom Hawks, the company that operates the Amazon PPC Optimizer application.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      These Terms of Service ("Terms", "Terms of Service") govern your use of our web application Amazon PPC Optimizer (the "Service") operated by Ecom Hawks ("us", "we", or "our").
                    </p>
                    <p className="text-muted-foreground mb-3">
                      Our Privacy Policy also governs your use of our Service and explains how we collect, safeguard and disclose information that results from your use of our web application. Please read it here: <a href="/privacy-policy" className="text-primary hover:underline">Privacy Policy</a>.
                    </p>
                    <p className="text-muted-foreground">
                      By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Definitions</h2>
                    <p className="text-muted-foreground mb-3">
                      <strong>SERVICE</strong> means the Amazon PPC Optimizer web application operated by Ecom Hawks.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      <strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                    </p>
                    <p className="text-muted-foreground mb-3">
                      <strong>USAGE DATA</strong> is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                    </p>
                    <p className="text-muted-foreground mb-3">
                      <strong>COOKIES</strong> are small pieces of data stored on your device (computer or mobile device).
                    </p>
                    <p className="text-muted-foreground mb-3">
                      <strong>DATA CONTROLLER</strong> means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      <strong>DATA SUBJECT (OR USER)</strong> is any living individual who is using our Service and is the subject of Personal Data.
                    </p>
                    <p className="text-muted-foreground">
                      <strong>AMAZON PPC DATA</strong> refers to the performance data, campaign settings, keywords, targeting, and other information related to your Amazon Advertising campaigns that you upload or allow to be accessed through our Service.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Communications</h2>
                    <p className="text-muted-foreground mb-3">
                      By using our Service, you agree to subscribe to newsletters, marketing or promotional materials and other information we may send. However, you may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing us at support@ecomhawks.com.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Updates to Terms</h2>
                    <p className="text-muted-foreground mb-3">
                      We reserve the right to modify these terms from time to time at our sole discretion. Therefore, you should review these pages periodically. When we change the Terms in a material manner, we will notify you that material changes have been made to the Terms. Your continued use of the Service after any such change constitutes your acceptance of the new Terms. If you do not agree to any of these terms or any future version of the Terms, do not use or access (or continue to access) the Service.
                    </p>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="account" className="mt-0">
                <div className="space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold mb-3">User Accounts</h2>
                    <p className="text-muted-foreground mb-3">
                      When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.
                    </p>
                    <p className="text-muted-foreground">
                      You may not use as a username the name of another person or entity or that is not lawfully available for use, a name or trademark that is subject to any rights of another person or entity other than you without appropriate authorization, or a name that is otherwise offensive, vulgar or obscene.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Subscription and Payment</h2>
                    <p className="text-muted-foreground mb-3">
                      Some parts of the Service are billed on a subscription basis. You will be billed in advance on a recurring basis, depending on the subscription plan you select.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      At the end of each billing period, your subscription will automatically renew under the same conditions unless you cancel it or Ecom Hawks cancels it. You may cancel your subscription either through your online account or by contacting our customer support team.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      All payments are processed securely through payment processors that comply with the PCI-DSS as managed by the PCI Security Standards Council. This is a set of requirements ensuring that all companies that process, store, or transmit credit card information maintain a secure environment.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      In case of payment failure due to card expiration, insufficient funds, or otherwise, we reserve the right to temporarily suspend your account until the payment is processed successfully. For accounts that remain unpaid for 30 days or more, we reserve the right to permanently terminate your account and delete your data.
                    </p>
                    <p className="text-muted-foreground">
                      We reserve the right to refuse or cancel your subscription at any time for reasons including but not limited to: service availability, errors in the description or price of the service, error in your order, or other reasons.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Refunds</h2>
                    <p className="text-muted-foreground mb-3">
                      We offer a 14-day money-back guarantee for new subscriptions. If you are not satisfied with our Service within the first 14 days of your subscription, you can request a full refund by contacting our support team at support@ecomhawks.com.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      Refunds for subscription renewals are generally not provided unless there has been an extended service outage or other substantial disruption to our Service. In such cases, refunds or credits may be provided at our discretion.
                    </p>
                    <p className="text-muted-foreground">
                      For any questions about refunds, please contact our customer support team.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Free Trial</h2>
                    <p className="text-muted-foreground mb-3">
                      We may, at our sole discretion, offer a free trial period for a limited time. If we do offer a free trial, we will specify the duration and limitations of the trial at sign-up.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      You may be required to enter your billing information in order to sign up for the free trial. In such cases, we will not bill you until the free trial period has expired. On the last day of the free trial period, unless you canceled your subscription, we will automatically bill you for the applicable subscription fees.
                    </p>
                    <p className="text-muted-foreground">
                      At any time and without notice, we reserve the right to (i) modify the terms and conditions of the free trial offer, or (ii) cancel such free trial offer.
                    </p>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="service" className="mt-0">
                <div className="space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold mb-3">Service Use and Restrictions</h2>
                    <p className="text-muted-foreground mb-3">
                      Our Service is designed to help users optimize their Amazon PPC advertising campaigns. You may use our Service only as permitted by law and according to these Terms. You agree that your use of the Service will not violate any rights of Ecom Hawks or any third party, including intellectual property rights such as copyright or trademark rights.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      By using our Service, you represent and warrant that:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1 mb-3">
                      <li>You have the legal right to use Amazon Advertising services in accordance with Amazon's terms of service</li>
                      <li>You have the legal right to provide us with any Amazon PPC Data that you upload or allow us to access</li>
                      <li>You are at least 18 years of age</li>
                      <li>You will not use our Service for any illegal or unauthorized purpose</li>
                      <li>Your use of the Service will not violate any applicable law or regulation</li>
                    </ul>
                    <p className="text-muted-foreground">
                      If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Service (or any portion thereof).
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Prohibited Activities</h2>
                    <p className="text-muted-foreground mb-3">
                      You may not access or use the Service for any purpose other than that for which we make the Service available. The Service may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      As a user of the Service, you agree not to:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1 mb-3">
                      <li>Systematically retrieve data or other content from the Service to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us</li>
                      <li>Make any unauthorized use of the Service, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses</li>
                      <li>Use the Service to advertise or offer to sell goods and services</li>
                      <li>Circumvent, disable, or otherwise interfere with security-related features of the Service, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Service and/or the Content contained therein</li>
                      <li>Engage in unauthorized framing of or linking to the Service</li>
                      <li>Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords</li>
                      <li>Make improper use of our support services or submit false reports of abuse or misconduct</li>
                      <li>Engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools</li>
                      <li>Interfere with, disrupt, or create an undue burden on the Service or the networks or services connected to the Service</li>
                      <li>Attempt to impersonate another user or person or use the username of another user</li>
                      <li>Use any information obtained from the Service in order to harass, abuse, or harm another person</li>
                      <li>Use the Service as part of any effort to compete with us or otherwise use the Service and/or the Content for any revenue-generating endeavor or commercial enterprise</li>
                      <li>Decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Service</li>
                      <li>Attempt to bypass any measures of the Service designed to prevent or restrict access to the Service, or any portion of the Service</li>
                      <li>Harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Service to you</li>
                      <li>Delete the copyright or other proprietary rights notice from any Content</li>
                      <li>Copy or adapt the Service's software, including but not limited to Flash, PHP, HTML, JavaScript, or other code</li>
                      <li>Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party's uninterrupted use and enjoyment of the Service or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Service</li>
                      <li>Upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats ("gifs"), 1×1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as "spyware" or "passive collection mechanisms" or "pcms")</li>
                      <li>Except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Service, or using or launching any unauthorized script or other software</li>
                      <li>Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Service</li>
                      <li>Use the Service in a manner inconsistent with any applicable laws or regulations</li>
                    </ul>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Service Modifications</h2>
                    <p className="text-muted-foreground mb-3">
                      We reserve the right to withdraw or amend our Service, and any service or material we provide via the Service, in our sole discretion without notice. We will not be liable if for any reason all or any part of the Service is unavailable at any time or for any period.
                    </p>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="limitations" className="mt-0">
                <div className="space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold mb-3">Disclaimer of Warranties</h2>
                    <p className="text-muted-foreground mb-3">
                      THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      WE DO NOT WARRANT THAT (1) THE SERVICE WILL MEET YOUR SPECIFIC REQUIREMENTS, (2) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (3) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (4) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS, OR (5) ANY ERRORS IN THE SERVICE WILL BE CORRECTED.
                    </p>
                    <p className="text-muted-foreground">
                      ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DONE AT YOUR OWN DISCRETION AND RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Limitation of Liability</h2>
                    <p className="text-muted-foreground mb-3">
                      TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL ECOM HAWKS, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS OR LICENSORS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THE USE OF, OR INABILITY TO USE, THIS SERVICE.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      WITHOUT LIMITING THE FOREGOING, ECOM HAWKS SHALL HAVE NO LIABILITY FOR ANY DAMAGES OR LOSSES RESULTING FROM: (1) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES; (2) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (3) ANY INCORRECT OR INACCURATE INFORMATION, WHETHER CAUSED BY YOU, AMAZON ADVERTISING, OUR ERRORS OR OMISSIONS OR BY ANY OF THE EQUIPMENT OR PROGRAMMING ASSOCIATED WITH OR UTILIZED IN THE SERVICE; (4) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; (5) THE TERMINATION OF YOUR ACCOUNT IN ACCORDANCE WITH THE TERMS; (6) ANY OTHER MATTER RELATING TO THE SERVICE.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE AGGREGATE LIABILITY OF ECOM HAWKS, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY, STRICT LIABILITY OR OTHER THEORY, ARISING OUT OF OR RELATING TO THE USE OF OR INABILITY TO USE THE SERVICE EXCEED THE AMOUNT PAID BY YOU FOR USING THE SERVICE DURING THE 12 MONTHS IMMEDIATELY PRECEDING THE CLAIM OR $100.00, WHICHEVER IS GREATER.
                    </p>
                    <p className="text-muted-foreground">
                      SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OR EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU TO THE EXTENT PROHIBITED BY LAW.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">External Resources</h2>
                    <p className="text-muted-foreground mb-3">
                      The Service may contain links to third-party web sites or services that are not owned or controlled by Ecom Hawks.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      Ecom Hawks has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that Ecom Hawks shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.
                    </p>
                    <p className="text-muted-foreground">
                      We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Service Availability</h2>
                    <p className="text-muted-foreground mb-3">
                      We aim to provide the best service possible, but we make no promise that the Service will meet your requirements or expectations. We cannot guarantee that the Service will be uninterrupted, timely, or error-free, or that defects will be corrected.
                    </p>
                    <p className="text-muted-foreground">
                      We reserve the right to suspend or terminate the Service at any time, with or without notice. We shall not be liable if, for any reason, all or any part of the Service is unavailable at any time or for any period.
                    </p>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="intellectual" className="mt-0">
                <div className="space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold mb-3">Intellectual Property Rights</h2>
                    <p className="text-muted-foreground mb-3">
                      The Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of Ecom Hawks and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Ecom Hawks.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">User Content</h2>
                    <p className="text-muted-foreground mb-3">
                      You retain your rights to any content you submit, post or display on or through the Service, including your Amazon PPC Data.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      By submitting, posting or displaying content on or through the Service, you grant us a worldwide, non-exclusive, royalty-free license (with the right to sublicense) to use, copy, reproduce, process, adapt, modify, publish, transmit, display and distribute such content in any and all media or distribution methods (now known or later developed) for the purpose of providing the Service to you. This license authorizes us to make your content available to the rest of the world and to let others do the same.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      You agree that this license includes the right for Ecom Hawks to provide, promote, and improve the Service and to make content submitted to or through the Service available to other companies, organizations or individuals for the syndication, broadcast, distribution, promotion or publication of such content on other media and services, subject to our terms and conditions for such content use.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      You represent and warrant that you have all the rights, power and authority necessary to grant the rights granted herein to any content that you submit. You also represent that the use and publication of such content will not violate the rights of any third party.
                    </p>
                    <p className="text-muted-foreground">
                      Ecom Hawks does not claim ownership in any of your content, including any text, data, information, images, photographs, music, sound, video, or other material, that you upload, transmit or store in your account. We will only use your content to provide the Service to you and as otherwise described in these Terms and our Privacy Policy.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">DMCA Compliance</h2>
                    <p className="text-muted-foreground mb-3">
                      We respect the intellectual property rights of others. It is our policy to respond to any claim that Content posted on the Service infringes the copyright or other intellectual property rights ("Infringement") of any person.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      If you are a copyright owner, or authorized on behalf of one, and you believe that the copyrighted work has been copied in a way that constitutes copyright infringement that is taking place through the Service, you must submit your notice in writing to the attention of "Copyright Infringement" at support@ecomhawks.com and include in your notice the following information:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1 mb-3">
                      <li>an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest;</li>
                      <li>a description of the copyrighted work that you claim has been infringed, including the URL (i.e., web page address) of the location where the copyrighted work exists or a copy of the copyrighted work;</li>
                      <li>identification of the URL or other specific location on the Service where the material that you claim is infringing is located;</li>
                      <li>your address, telephone number, and email address;</li>
                      <li>a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;</li>
                      <li>a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf.</li>
                    </ul>
                    <p className="text-muted-foreground">
                      We can be reached at: support@ecomhawks.com
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Feedback</h2>
                    <p className="text-muted-foreground mb-3">
                      We welcome feedback, comments and suggestions for improvements to the Service ("Feedback"). You acknowledge and expressly agree that any contribution of Feedback does not and will not give or grant you any right, title or interest in the Service or in any such Feedback.
                    </p>
                    <p className="text-muted-foreground">
                      All Feedback becomes the sole and exclusive property of Ecom Hawks, and Ecom Hawks may use and disclose Feedback in any manner and for any purpose whatsoever without further notice or compensation to you and without retention by you of any proprietary or other right or claim.
                    </p>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="legal" className="mt-0">
                <div className="space-y-6">
                  <div>
                    <h2 className="text-xl font-semibold mb-3">Termination</h2>
                    <p className="text-muted-foreground mb-3">
                      We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service, or contact us at support@ecomhawks.com to request account deletion.
                    </p>
                    <p className="text-muted-foreground">
                      All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Indemnification</h2>
                    <p className="text-muted-foreground mb-3">
                      You agree to defend, indemnify and hold harmless Ecom Hawks and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service, by you or any person using your account and password; b) a breach of these Terms, or c) Content posted on the Service.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Governing Law</h2>
                    <p className="text-muted-foreground mb-3">
                      These Terms shall be governed and construed in accordance with the laws of the State of California, United States, without regard to its conflict of law provisions.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Dispute Resolution</h2>
                    <p className="text-muted-foreground mb-3">
                      If you have any concern or dispute about the Service, you agree to first try to resolve the dispute informally by contacting us at support@ecomhawks.com.
                    </p>
                    <p className="text-muted-foreground mb-3">
                      If a dispute cannot be resolved informally, you and Ecom Hawks agree to resolve any dispute, controversy, or claim arising out of or in connection with these Terms, including the breach, termination or validity thereof (a "Dispute"), in accordance with the following procedure:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1 mb-3">
                      <li>Either party may initiate this procedure by sending written notice of the Dispute to the other party.</li>
                      <li>Following notice, the parties shall attempt to resolve the Dispute through negotiation.</li>
                      <li>If the Dispute has not been resolved by negotiation within 30 days of the notice, the parties agree to submit the Dispute to mediation administered by JAMS in accordance with its mediation procedures.</li>
                      <li>If the Dispute is not resolved through mediation within 90 days of the notice, either party may commence legal proceedings.</li>
                    </ul>
                    <p className="text-muted-foreground mb-3">
                      Notwithstanding the foregoing, either party may seek injunctive or other equitable relief in any court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of that party's intellectual property rights.
                    </p>
                    <p className="text-muted-foreground">
                      The parties agree that the courts located in San Francisco County, California shall have exclusive jurisdiction to settle any Dispute that is permitted to be brought in court pursuant to these Terms.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">No Class Actions</h2>
                    <p className="text-muted-foreground mb-3">
                      ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER.
                    </p>
                  </div>

                  <div>
                    <h2 className="text-xl font-semibold mb-3">Contact Us</h2>
                    <p className="text-muted-foreground mb-3">
                      If you have any questions about these Terms, please contact us:
                    </p>
                    <ul className="list-disc pl-6 text-muted-foreground space-y-1">
                      <li>By email: support@ecomhawks.com</li>
                      <li>By phone: +1 (555) 123-4567</li>
                      <li>By mail: Ecom Hawks, 123 Market Street, Suite 456, San Francisco, CA 94105</li>
                    </ul>
                  </div>
                </div>
              </TabsContent>
            </ScrollArea>
          </CardContent>
        </Card>
      </Tabs>

      <div className="flex justify-between items-center p-4 bg-primary/5 border border-primary/10 rounded-lg">
        <div className="flex items-center space-x-3">
          <Clock className="h-5 w-5 text-muted-foreground" />
          <p className="text-sm text-muted-foreground">
            These terms of service were last updated on {lastUpdated}.
          </p>
        </div>
        <div className="flex items-center space-x-3">
          <Button variant="outline" size="sm" asChild>
            <a href="/privacy-policy">
              <Shield className="h-4 w-4 mr-2" />
              Privacy Policy
            </a>
          </Button>
        </div>
      </div>
    </div>
  );
}